name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16" # Node 버전을 필요에 따라 변경

            - name: Install dependencies
              run: npm install

            - name: Build project
              env:
                  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
                  REACT_APP_GOOGLE_CLIENT_SECRET_KEY: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET_KEY }}
                  REACT_APP_GOOGLE_REDIRECT_URI: ${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI }}
                  REACT_APP_GOOGLE_SHEET_URI: ${{ secrets.REACT_APP_GOOGLE_SHEET_URI }}
                  REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}
                  REACT_APP_KAKAO_REDIRECT_URI: ${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}
              run: npm run build

            - name: Deploy to GitHub pages
              uses: peaceiris/gh-pages-action@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
